test: L2 to L1 withdrawal
0xPolygon/cdk pull request #126
Opened 2024-10-14 16:11 UTC by vcastellm

L2 to L1 withdrawal test

2024-10-22 09:22 UTC, Stefan-Ethernal commented on test/helpers/common.bash
> +    local gas_token_addr="$2"      # gas token contract address
I'd consider to rename it just to `token_addr` if you agree (and if there are not naming collisions)?
```suggestion
    local token_addr="$2"      # fungible token contract address
```

2024-10-22 09:22 UTC, Stefan-Ethernal commented on test/helpers/lxly-bridge-test.bash
>  function deposit() {
Shall we rename this to `bridgeAsset`, since it is used for withdrawals as well. WDYT?

2024-10-22 09:22 UTC, Stefan-Ethernal commented on test/bridge-e2e.bats
> +    readonly bridge_sig='bridgeAsset(uint32,address,uint256,address,bool,bytes)'
We can keep it in the `deposit` function in the `lxly-bridge-test.bash`, since it is used only in that one. WDYT?

2024-10-24 09:00 UTC, leovct commented on .github/workflows/test-e2e.yml
> +      run: kurtosis dump ./dump
```suggestion
      run: kurtosis enclave dump cdk ./dump
```

2024-10-24 09:15 UTC, Stefan-Ethernal approved these changes

2024-10-24 10:00 UTC, ToniRamirezM requested changes
Please make Checking PR semantic rule pass.

2024-10-24 10:05 UTC, vcastellm commented on test/combinations/fork11-rollup.yml
> -    - pless_zkevm_node
nah, not used in the tests and also removed in kurtosis-cdk

2024-10-24 10:06 UTC, vcastellm commented on .github/workflows/test-e2e.yml
> +      run: kurtosis dump ./dump
introduced in the latest commit

2024-10-24 10:06 UTC, vcastellm commented on .github/workflows/test-e2e.yml
> +        kurtosis service exec cdk cdk-node-001 'cat /etc/cdk/cdk-node-config.toml' > ./dump/cdk-node-config.toml
outdated

2024-10-24 10:07 UTC, vcastellm commented on test/helpers/lxly-bridge-test.bash
> +    cat $bridge_deposit_file >&3
good catch, no

2024-10-24 10:08 UTC, vcastellm commented on test/helpers/lxly-bridge-test.bash
> +            echo "cast send --legacy --gas-price $comp_gas_price --rpc-url $destination_rpc_url --private-key $sender_private_key $bridge_addr \"$claim_sig\" \"$in_merkle_proof\" \"$in_rollup_merkle_
it's not needed but I prefer to leave it for convenience, wdyt?

2024-10-24 11:26 UTC, ToniRamirezM approved these changes

2024-10-24 11:59 UTC, rbpol approved these changes

2024-10-24 12:45 UTC, merged