fix: l1infotreesync TestStressAndReorg
0xPolygon/cdk pull request #137
Opened 2024-10-21 23:32 UTC by rbpol

Fixing l1infotreesync TestStressAndReorg

2024-10-22 19:25 UTC, rachit77 approved these changes

2024-10-25 22:27 UTC, arnaubennassar requested changes

2024-10-25 22:27 UTC, arnaubennassar commented on l1infotreesync/e2e_test.go
> +	t.Skip()
I'm working on syncing the `UpdateL1InfoTreeV2` event, which adds a sanity check on the expected root. This test makes the sanity check fail consistently...

I suspect that there is a problem with either the reorg detector, the processor or the integration of those.

Please do NOT merge this until I've figured this out... As I may end up finding the root of the problem 🤔

2024-11-15 11:55 UTC, goran-ethernal commented
Closing this since the flaky test was fixed in: https://github.com/0xPolygon/cdk/pull/182

2024-11-15 11:55 UTC, closed without merging