feat: epoch notifier
0xPolygon/cdk pull request #144
Opened 2024-10-25 20:03 UTC by joanestebanr

## Description

Please include a summary of the change and which issue is fixed. Also, include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

2024-10-28 08:41 UTC, goran-ethernal commented on cmd/run.go
> +		aggsender.ConfigEpochNotifierPerBlock{
I think we should move the two configs for notifiers to the real config, and make it a part of `Aggsender` config part in `.toml` files, like:

```
[Aggsender.EpochNotifier]
BlockFinality = "Latest"
CheckNewBlockInterval = "1s"
StartingEpochBlock = 1000
EpochSize = 10
BlocksBeforeEpochEnding = 2
```

2024-10-28 08:41 UTC, goran-ethernal commented on cmd/run.go
> +			StartingEpochBlock:                0,
I think we need to set this to a non zero value. I've raised this question with the agglayer team couple of weeks ago, but didn't get the right response. We need to know from which L1 block the agglayer starts counting epochs. If they start let's say at block 1010, and we don't set the `StartingEpochBlock` to this, we might get wrong results when calculating epoch and when to send a certificate.

2024-10-28 08:41 UTC, goran-ethernal commented on aggsender/types/generic_subscriber.go
> +type SubscriptionHandler[T any] struct {
Is this used? I can't seem to find any usage of this struct.

2024-10-28 08:41 UTC, goran-ethernal commented on aggsender/types/epoch_notifier.go
> +type EpochEvent struct {
If we only need the epoch then I would remove this event, and just return an `uint64` in the channel.

2024-10-28 13:59 UTC, joanestebanr commented on aggsender/types/generic_subscriber.go
> +type SubscriptionHandler[T any] struct {
You're right no longer used!

2024-10-28 14:00 UTC, joanestebanr commented on aggsender/types/epoch_notifier.go
> +type EpochEvent struct {
I prefer the struct because we can add more info in a easy way if we need and also is 'hard' type

2024-10-28 15:48 UTC, joanestebanr commented on cmd/run.go
> +		aggsender.ConfigEpochNotifierPerBlock{
I think that is better to keep config-file simple: the internal structure it's better to be decoupled with config-file

2024-10-28 16:54 UTC, arnaubennassar requested changes

2024-10-28 16:54 UTC, arnaubennassar commented on aggsender/block_notifier_polling.go
> +	go b.start(ctx)
In general, the pattern is to let the `cmd` or other "top level" package to decide when to use `go`.

So I'd suggest to remove this function and make public the `start` func

2024-10-28 16:54 UTC, arnaubennassar commented on aggsender/epoch_notifier_per_block.go
> +	EthereumBlockSpeed = time.Second * 15
```suggestion
	EthereumBlockSpeed = time.Second * 12
```

2024-10-29 08:12 UTC, joanestebanr commented on aggsender/epoch_notifier_per_block.go
> +	EthereumBlockSpeed = time.Second * 15
You're right! but I'll remove this const because is no longer used, the sampling frequency is calculated dynamically

2024-10-29 08:19 UTC, joanestebanr commented on aggsender/block_notifier_polling.go
> +	go b.start(ctx)
Ok, I see  that `AggSender` have the same issue:  launch the go routines inside the `Start` call, In that case it launch 2 go routines. How do you suggest to fix that?

2024-10-29 10:48 UTC, vcastellm commented on aggsender/block_notifier_polling.go
> +func NewBlockNotifierPolling(ethClient types.EthClient,
Can you add a description of what this does?

2024-10-29 11:08 UTC, vcastellm commented on aggsender/block_notifier_polling.go
> +	go b.start(ctx)
Could be the same, move the go routines to the top level?

2024-10-30 08:48 UTC, goran-ethernal commented on agglayer/client.go
> +func (c *AggLayerClient) GetClockConfiguration() (*ClockConfiguration, error) {
Add a comment to this function, to be consistent with others in this file.

2024-10-30 08:48 UTC, goran-ethernal commented on agglayer/types.go
> +type ClockConfiguration struct {
Add comments to be consistent with other structs and functions in the file.

2024-10-30 08:48 UTC, goran-ethernal commented on cmd/run.go
> +	epochNotifier, err := aggsender.NewEpochNotifierPerBlock(
Should we start the epoch notifier here. I don't see it being started anywhere.

2024-10-30 08:48 UTC, goran-ethernal commented on cmd/run.go
> +		BlockFinalityType:     etherman.LatestBlock,
I am unsure about polling the latest block. We might need to check how agglayer does this, and how they count blocks in epoch. Do they poll for latest or finalized blocks.

2024-10-30 09:34 UTC, joanestebanr commented on cmd/run.go
> +		BlockFinalityType:     etherman.LatestBlock,
maybe we can move that to configuration

2024-10-30 11:11 UTC, goran-ethernal commented on cmd/run.go
> +		BlockFinalityType:     etherman.LatestBlock,
I've saw their answer. Its Latest block, so we are ok.

2024-10-31 15:48 UTC, goran-ethernal approved these changes

2024-11-04 16:04 UTC, vcastellm approved these changes
LGTM

2024-11-04 16:08 UTC, vcastellm commented on aggsender/block_notifier_polling_test.go
> +	t.Skip()
should we remove?

2024-11-07 11:30 UTC, joanestebanr commented on aggsender/block_notifier_polling_test.go
> +	t.Skip()
it's a exploratory test, just for test it if we need

2024-11-11 14:43 UTC, vcastellm commented on test/bridge-e2e.bats
> +@test "transfer ETH L1 to L2 to L1" {
You can merge this with `"Native gas token deposit to WETH"` tests at the top of the file as commented

2024-11-11 17:09 UTC, vcastellm commented on aggsender/types/block_notifier.go
> +	// NotifyEpochStarted notifies the epoch has started.
Does this line belongs to here?

2024-11-11 17:10 UTC, vcastellm requested changes
Observe some new comments

2024-11-11 17:29 UTC, joanestebanr commented on aggsender/types/block_notifier.go
> +	// NotifyEpochStarted notifies the epoch has started.
The interface `BlockNotifier` is the interface that use `EpochNotifierPerBlock`. Now there are 1 implementation that is `BlockNotifierPolling` but the idea is to create another one  using WS and decide in runtime which one to use

2024-11-12 09:10 UTC, goran-ethernal commented on aggsender/aggsender.go
>  func (a *AggSender) checkPendingCertificatesStatus(ctx context.Context) {
I think we need to change this function to `anyPendingCertificates` and return a bool and an error. Bool meaning if we have pending certificates, and error, if some error occurs while checking. Then if the bool is true, we just continue the loop in `sendCertificates`, and if error, just log it and continue the loop.

If we leave it as it is now, we can have pending certificates, and we will try to send a new one.

2024-11-12 09:28 UTC, joanestebanr commented on agglayer/client.go
> +	jSONRPCCall                  = rpc.JSONRPCCall
Yes, is for unittest the client

2024-11-12 11:09 UTC, vcastellm approved these changes

2024-11-12 11:20 UTC, merged