feat: sync UpdateL1InfoTreeV2
0xPolygon/cdk pull request #145
Opened 2024-10-25 22:58 UTC by arnaubennassar

## Description

Sync the `UpdateL1InfoTreeV2` event. This event shares info to be used as a sanity check. If the sanity check fails it means that the syncer failed to sync the L1 info tree in a fatal way.

However this could be caused due to a reorg that has not been detected yet. In fact, one of the reorg tests was failing because of that. That's why I've implemented this in a way that halts the syncer instead of returning an error: to give the syncer the opportunity to get reorged. Note that if the sanity check fails for other reasons that are not reorg, this means that the syncer code has a fatal bug innit

2024-10-28 14:52 UTC, joanestebanr commented on l1infotreesync/processor.go
> +	CurrentL1InfoRoot [32]byte
maybe can change type of `CurrentL1InfoRoot`  to `Common.Hash`

2024-10-28 16:56 UTC, arnaubennassar commented on l1infotreesync/processor.go
> +				return nil
please have a look at the comment I left a few lines above:

```
// If the sanity check fails, halt the syncer and rollback. The sanity check could have
// failed due to a reorg. Hopefully, this is the case, eventually the reorg will get detected,
// and the syncer will get unhalted. Otherwise, this means that the syncer has an inconsistent state
// compared to the contracts, and this will need manual intervention.
// Do not return an error to give the driver the opportunity to detect a reorg
```

2024-10-31 17:25 UTC, joanestebanr requested changes
It needs also to prevent to use wrong data, returning error to the query functions of processor

2024-11-04 17:48 UTC, joanestebanr approved these changes

2024-11-07 09:12 UTC, joanestebanr approved these changes

2024-11-08 16:18 UTC, arnaubennassar commented on l1infotreesync/processor.go
> +					root.Index, event.UpdateL1InfoTreeV2.LeafCount,
I dont get it, both the index or the hash could be wrong

2024-11-08 17:03 UTC, Stefan-Ethernal approved these changes

2024-11-08 17:34 UTC, merged