Feat/reorg test bridge
0xPolygon/cdk pull request #190
Opened 2024-11-14 19:16 UTC by arnaubennassar

## Description

Please include a summary of the change and which issue is fixed. Also, include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

2024-11-20 08:20 UTC, goran-ethernal approved these changes

2024-11-20 08:20 UTC, goran-ethernal commented on test/helpers/reorg.go
> +	log.Debugf("reorging until block %d. Current block %d (before reorg)", block.NumberU64(), currentBlockNum)
Move this after the require no error.

2024-11-21 11:49 UTC, vcastellm approved these changes
LGTM

2024-11-21 13:21 UTC, joanestebanr requested changes
why do you need a real file on unittest?

2024-11-21 13:24 UTC, goran-ethernal commented on aggsender/db/aggsender_db_storage_test.go
> +	path := path.Join(t.TempDir(), "aggsenderTest_Storage.sqlite")
I've seen this in the aggsender tests, that is why I've added that clean function.

2024-11-21 16:26 UTC, arnaubennassar commented on aggsender/db/aggsender_db_storage_test.go
> +	path := path.Join(t.TempDir(), "aggsenderTest_Storage.sqlite")
yes, I faced problems making things work in memory in the past + it was already using file!

Other than that, let's try to have as realistic tests as possible. It's ok to mock when it facilitates testing, but in this case, having a more realistic setup is super easy and doesn't add friction. The way sqlite is configured has a huge impact on how it works: some tests broke when I changed the config, so I believe we should aim to have the same setup on tests vs on prod

2024-11-22 13:00 UTC, joanestebanr approved these changes

2024-11-29 17:10 UTC, merged