feat(aggsender): add more data to certificate metadata
0xPolygon/cdk pull request #200
Opened 2024-11-26 12:03 UTC by vcastellm

## Description

Please include a summary of the change and which issue is fixed. Also, include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

2024-11-28 15:31 UTC, Stefan-Ethernal approved these changes

2024-11-28 15:47 UTC, joanestebanr requested changes
Please, fill the PR description

2024-11-28 15:47 UTC, joanestebanr commented on aggsender/aggsender.go
> +func createCertificateMetadata(fromBlock, toBlock, createdAt uint64) common.Hash {
Maybe as parameter you can use `types.CertificateMetadata`

2024-11-28 15:47 UTC, joanestebanr commented on aggsender/aggsender.go
> +		UpdatedAt:         meta.CreatedAt,
I think that this must be now

2024-11-28 17:05 UTC, vcastellm commented
> Please, fill the PR description

thx, forgot about it when moving out of draft, done.

2024-11-28 17:30 UTC, vcastellm commented on aggsender/aggsender.go
> +func createCertificateMetadata(fromBlock, toBlock, createdAt uint64) common.Hash {
that's one possibility I considered but now that you mention it can be even better abstracted, see https://github.com/0xPolygon/cdk/pull/200/commits/b7950e906992bc8805cb04676bcbffaf4e2fbb7b wdyt?

2024-11-29 07:53 UTC, joanestebanr commented on aggsender/aggsender.go
> +		UpdatedAt:         meta.CreatedAt,
Yes, it is. The `updateAt` is store the moment that `aggsender` write some update on this row, that is the idea.

2024-11-29 08:14 UTC, vcastellm commented on aggsender/aggsender.go
> +		UpdatedAt:         meta.CreatedAt,
makes sense

2024-11-29 08:23 UTC, joanestebanr approved these changes

2024-11-29 11:47 UTC, merged