refactor: encode metadata to be backwards compatible
0xPolygon/cdk pull request #216
Opened 2024-12-03 09:55 UTC by vcastellm

Refactoring the encoding of the values into the metadata field makes it compatible with the previously existing values, added a test for that.

Also moving tests to the types package where it belongs.

2024-12-03 10:55 UTC, Stefan-Ethernal commented on aggsender/types/types.go
> +func NewCertificateMetadata(toBlock, fromBlock, createdAt uint64) *CertificateMetadata {
IMO it is more intuitive to provide the `fromBlock` as the first parameter (although we are encoding the `toBlock` first). WDYT?

```suggestion
func NewCertificateMetadata(fromBlock, toBlock, createdAt uint64) *CertificateMetadata {
```

2024-12-03 10:55 UTC, Stefan-Ethernal commented on aggsender/types/types.go
> +	binary.BigEndian.PutUint64(b[8:16], c.CreatedAt)
Maybe add some comment, that prior to #200, we were encoding just the `ToBlock` and that's why we are skipping the first 8 bytes...?

Although _probably_ it is worth considering versioning metadata (add the version field and act accordingly). WDYT?

2024-12-03 11:23 UTC, vcastellm commented on aggsender/types/types.go
> +	binary.BigEndian.PutUint64(b[8:16], c.CreatedAt)
ok to 1.

Versioning doesn't makes much sense to me as there's only 8 bytes of space left, if we add versioning we'll use all space, no space for more changes. I think it's worth handling changes here and keeping those 8 bytes free for the future.

2024-12-03 12:41 UTC, Stefan-Ethernal commented on aggsender/types/types.go
>  	)
Shouldn't this function decode the certificate metadata with the old format (namely, support the format where the `toBlock` field occupied the first 8 bytes)?

2024-12-04 10:08 UTC, joanestebanr requested changes
Please, merge it at `release/v0.5.0`

2024-12-04 10:08 UTC, joanestebanr commented on aggsender/types/types.go
>  	)
I think that requires to set the 'createAt` to `now` if it's the previous metadata version

2024-12-04 10:10 UTC, joanestebanr commented on aggsender/types/types.go
> +	binary.BigEndian.PutUint64(b[8:16], c.CreatedAt)
I agree with @Stefan-Ethernal , we need to versioning metadata... We need to think in a way of doing this

2024-12-04 11:28 UTC, vcastellm commented
> Please, merge it at `release/v0.5.0`

Instead of rebasing, let's merge it to `develop` then I'll cherry-pick to `v0.5.0`

2024-12-04 11:30 UTC, vcastellm commented on aggsender/types/types.go
>  	)
This is decoding @joanestebanr, so we need to take what's in `hash`.

2024-12-04 11:30 UTC, vcastellm commented on aggsender/types/types.go
> +	binary.BigEndian.PutUint64(b[8:16], c.CreatedAt)
Do you prefer to ocuppy the remaining 8 bytes with the version?

2024-12-05 11:09 UTC, vcastellm commented
Rebased onto `release/v0.5.0` @joanestebanr

2024-12-05 12:37 UTC, joanestebanr commented on aggsender/aggsender.go
> +		toBlock = meta.ToBlock
The `createdAt` need to be set to `now`

2024-12-05 12:37 UTC, joanestebanr commented on aggsender/aggsender.go
> +		CreatedAt:         int64(meta.CreatedAt),
maybe make sense to change the type of `CertificateInfo` for tstamp to `uint32` all of them, WDYT?

2024-12-05 12:38 UTC, joanestebanr approved these changes

2024-12-05 16:21 UTC, vcastellm commented on aggsender/aggsender.go
> +		CreatedAt:         int64(meta.CreatedAt),
agree

2024-12-06 15:14 UTC, Stefan-Ethernal approved these changes

2024-12-06 15:25 UTC, merged