feat: agg-sender
0xPolygon/cdk pull request #22
Opened 2024-07-26 12:03 UTC by goran-ethernal

## Description

This PR implements the `Aggsender` component which is tasked of sending certificates to the `agglayer` using the `interop_sendCeritificate` rpc endpoint.

### Config
Next code is an example of the `Aggsender`  configuration:

```
[AggSender]
DBPath = "/tmp/aggsender" // path of the SQLite DB for the aggsender
AggLayerURL = "http://zkevm-agglayer" // URL to the agglayer
AggsenderPrivateKey = {Path = "/pk/sequencer.keystore", Password = "testonly"} // Aggsender private key that will sign the certificates before sending them to the agglayer
BlockGetInterval = "2s" // Interval for getting L1 blocks
URLRPCL2="http://test-aggoracle-l2:8545" // L2 node RPC URL
CheckSettledInterval = "2s" // Interval in which aggsender will check if sent certificates are settled
SaveCertificatesToFiles = false // indicates if sent certificates should be save to json files (for debugging purposes)
```

### Required components (services)

The `aggsender` utilizes next components in the cdk repo to build a certificate:

1. `L1 client` to get L1 blocks - certificates are settled on agglayer one by CDK in a single L1 epoch (configured by the `EpochSize` in the config), so we need to know how many L1 blocks have passed so we can send another certificate.
2. `L2 client` - to get the last block on the L2. This is needed to know to which block we get claims and bridges on L2 to send them in a certificate.
3. `L2 bridge syncer` - to get bridges, claims and blocks on L2, needed for a certificate.
4. `L1 info tree syncer` - to build inclusion proofs.
5. `Agglayer client` - needed to send certificates to the agglayer, and check if sent certificates were settled on the agglayer.

### DB

`Aggsender` saves sent certificates in its local `SQLite` db. It has one table called `certificate_info` in which it saves this data:

```go
type CertificateInfo struct {
	Height           uint64                     `meddler:"height"`
	CertificateID    common.Hash                `meddler:"certificate_id"`
	NewLocalExitRoot common.Hash                `meddler:"new_local_exit_root"`
	FromBlock        uint64                     `meddler:"from_block"`
	ToBlock          uint64                     `meddler:"to_block"`
	Status           agglayer.CertificateStatus `meddler:"status"`
}
```
`Height` - is a simple counter of this cdk's certificates. We can look at it as a nonce. It gets incremented by sending and settling certificates.
`CertificateID` - certificates Hash.
`NewLocalExitRoot `- new local exit root posted through the certificate (gotten from l2 bridge syncer).
`FromBlock` - block from which we got bridges and claims on L2.
`ToBlock` - block to which we got bridges and claims on L2.
`Status` - certificate status on `agglayer`. It can be `Pending` (pending to be settled), `Settled`, or `InError` (if some error happens on certificate settling).

### Flow

![image](https://github.com/user-attachments/assets/e616d121-022d-41d2-9c6b-16e11025f4a8)

2024-09-24 07:25 UTC, goran-ethernal commented on aggsender/aggsender.go
> +	go a.sendCertificates(ctx)
Fix: https://github.com/0xPolygon/cdk/pull/22/commits/0add101f9452c09ed3e36baca5833199a1645533

2024-09-24 07:25 UTC, goran-ethernal commented on aggsender/aggsender.go
> +func (a *AggSender) sendCertificatesForNetwork(ctx context.Context) error {
Fix: https://github.com/0xPolygon/cdk/pull/22/commits/0add101f9452c09ed3e36baca5833199a1645533

2024-09-24 07:31 UTC, goran-ethernal commented on aggsender/aggsender.go
> +		bridgeExit := convertBridgeToBridgeExit(bridge)
I know, I was just throwing code, since it is being changed on regular basis by the agglayer team. In the newest commit: https://github.com/0xPolygon/cdk/pull/22/commits/0add101f9452c09ed3e36baca5833199a1645533, you will see that they changed the API structure quite a bit, especially in regards to the `L1InfoTreeLeaves` and `MerkleProofs`, so I don't think we can change the `bridgesync` to work with agglayer API types. I mean, we could, but it won't have all the data, so I am not a fan of this approach. 

The second approach of custom marshaller is also not a good idea, because of the data we collect after we get bridges and claims from the `bridgesync`, the proofs, the global exit root, block timestamp, block hash, etc.

I am not sure what would be the right approach. Maybe changing the `bridgesync` would be the easiest and the correct approach.

2024-09-24 07:32 UTC, goran-ethernal commented on aggsender/aggsender.go
> +	return nil
Indeed. We will remove this database code in `aggsender` after they introduce the new endpoint to get the latest submitted certificate, as well as the change in the current one.

2024-10-11 14:13 UTC, goran-ethernal commented on aggsender/aggsender.go
> +	return nil
Implemented the `checkIfCertificatesAreSettled` function for this, based on the new endpoint on the `agglayer` called, `interop_getCertificateHeader`.

2024-10-17 07:55 UTC, goran-ethernal commented on aggsender/aggsender.go
> +	return (block+numOfBlocksBeforeEpochEnding)%a.cfg.EpochSize == 0
I agree, I am changing this currently, to not have this send interval, rather just pinging blocks, until we reach the desired one.

2024-10-21 14:03 UTC, goran-ethernal commented on aggsender/aggsender.go
> +	return (block+numOfBlocksBeforeEpochEnding)%a.cfg.EpochSize == 0
Fix: https://github.com/0xPolygon/cdk/pull/22/commits/8da0c737bd9dd4054d48ef97caa09fd4f77290f0

2024-10-22 06:44 UTC, goran-ethernal commented on agglayer/types.go
> +	)
They were before, but currently, they are not. These are left because of the old agglayer spec. I can remove it since they are not used.

2024-10-22 06:49 UTC, goran-ethernal commented on agglayer/types.go
> +	)
I see now they've had changes on the main branch that might use these functions, so I will leave them until we update again.

2024-10-22 06:50 UTC, goran-ethernal commented on agglayer/types.go
> +func (c *BridgeExit) Hash() common.Hash {
I will leave them, since there are changes on the agglayer main branch that use these functions, so we will need to update in the near future.

2024-10-22 06:54 UTC, goran-ethernal commented on aggsender/mock_eth_client.go
> +// Code generated by mockery v2.45.0. DO NOT EDIT.
We don't have a clear standard on this. Some packages have it in mocks folder, some don't. I will move it to mocks, but It is not something that is forced.

2024-10-22 07:00 UTC, goran-ethernal commented on agglayer/client.go
> +	GetCertificateHeader(certificateHash common.Hash) (*CertificateHeader, error)
We don't need that. Certificates are sent 1 per epoch, and epochs will be a reasonable size of blocks. Enough time to settle the sent certificate (or put it in InError), before we send another one.

2024-10-22 07:05 UTC, goran-ethernal commented on aggsender/db/migrations/migrations.go
> +var mig001 string
I would leave that for another PR, it requires a lot of changes.

2024-10-22 07:12 UTC, goran-ethernal commented on agglayer/types.go
> +	LeafTypeMessage LeafType = 1
Fix: https://github.com/0xPolygon/cdk/pull/22/commits/bdad93de39689ed43a97159102a10cbcf89b7f7c

2024-10-22 07:12 UTC, goran-ethernal commented on aggsender/types/types.go
> +	return fmt.Sprintf("Height: %d, CertificateID: %s", c.Height, c.CertificateID.String())
Fix: https://github.com/0xPolygon/cdk/pull/22/commits/bdad93de39689ed43a97159102a10cbcf89b7f7c

2024-10-22 07:12 UTC, goran-ethernal commented on aggsender/config.go
> +type Config struct {
Fix: https://github.com/0xPolygon/cdk/pull/22/commits/bdad93de39689ed43a97159102a10cbcf89b7f7c

2024-10-22 07:13 UTC, goran-ethernal commented on aggsender/aggsender.go
> +const numOfBlocksBeforeEpochEnding = 2
Fix: https://github.com/0xPolygon/cdk/pull/22/commits/bdad93de39689ed43a97159102a10cbcf89b7f7c

2024-10-22 07:13 UTC, goran-ethernal commented on aggsender/aggsender.go
> +	block, err := a.l1Client.BlockNumber(ctx)
Fix: https://github.com/0xPolygon/cdk/pull/22/commits/bdad93de39689ed43a97159102a10cbcf89b7f7c

2024-10-22 07:13 UTC, goran-ethernal commented on aggsender/aggsender.go
> +	a.log.Infof("certificate: %s sent successfully for block: %d to block: %d", certificateHash, fromBlock, toBlock)
Fix: https://github.com/0xPolygon/cdk/pull/22/commits/bdad93de39689ed43a97159102a10cbcf89b7f7c

2024-10-22 07:13 UTC, goran-ethernal commented on agglayer/types.go
> +	return fmt.Sprintf("Height: %d, CertificateID: %s", c.Height, c.CertificateID.String())
Fix: https://github.com/0xPolygon/cdk/pull/22/commits/bdad93de39689ed43a97159102a10cbcf89b7f7c

2024-10-22 07:13 UTC, goran-ethernal commented on aggsender/config.go
> +	SequencerPrivateKey  types.KeystoreFileConfig `mapstructure:"SequencerPrivateKey"`
Fix: https://github.com/0xPolygon/cdk/pull/22/commits/bdad93de39689ed43a97159102a10cbcf89b7f7c

2024-10-22 07:13 UTC, goran-ethernal commented on agglayer/client.go
> +		return common.Hash{}, fmt.Errorf("%v %v", response.Error.Code, response.Error.Message)
Fix: https://github.com/0xPolygon/cdk/pull/22/commits/bdad93de39689ed43a97159102a10cbcf89b7f7c

2024-10-22 07:13 UTC, goran-ethernal commented on agglayer/client.go
> +		return nil, fmt.Errorf("%v %v", response.Error.Code, response.Error.Message)
Fix: https://github.com/0xPolygon/cdk/pull/22/commits/bdad93de39689ed43a97159102a10cbcf89b7f7c

2024-10-22 07:32 UTC, goran-ethernal commented on aggsender/mock_eth_client.go
> +// Code generated by mockery v2.45.0. DO NOT EDIT.
Fix: https://github.com/0xPolygon/cdk/pull/22/commits/313cf7fccc42354520a70b5bdddaff22374d41b5

2024-10-22 07:41 UTC, joanestebanr approved these changes

2024-10-22 08:01 UTC, Stefan-Ethernal approved these changes

2024-10-23 20:51 UTC, arnaubennassar requested changes

2024-10-23 20:51 UTC, arnaubennassar commented on aggsender/aggsender.go
> +	l2Client         aggsendertypes.EthClient
we should avoid using a execution client in the aggSender. Doing so will couple the aggSender with the execution client, something that we want to avoid to keep thing modular. Basically having EVM stuff on the aggsender will complicate the integration of non-EVM stuff.

It looks like that removing this should be easy, if we relay on the last synced block for chosing the "to block"

2024-10-23 20:51 UTC, arnaubennassar commented on aggsender/aggsender.go
> +	bridges, err := a.l2Syncer.GetBridges(ctx, fromBlock, toBlock)
not sure how the len() == 0 is returned, maybe it's with the form of an error not found

2024-10-23 20:51 UTC, arnaubennassar commented on aggsender/aggsender.go
> +	claims, err := a.l2Syncer.GetClaims(ctx, fromBlock, toBlock)
same comment as the potential error not found as before, in this case that would be bad, as it's acceptable to not have claims and so we should proceed with the execution

2024-10-23 20:51 UTC, arnaubennassar commented on aggsender/aggsender.go
> +		lastSentCertificateHeader, err := a.aggLayerClient.GetCertificateHeader(lastSentCertificate.CertificateID)
I dont get this part, I thought it would be something like:
- if we have a last sent cert on the DB, return that (prolly after asserting that what we have is consistent with the aggLayer)
- else, get it from the aggLayer

But looks like if there is nothing on the DB we assume that there is nothing on the aggLayer, which may not be the case...

2024-10-23 20:51 UTC, arnaubennassar commented on aggsender/aggsender.go
> +func chooseToL2Block(lastL2Block, lasL2BlockSynced, lastCertificateBlock uint64) (uint64, error) {
If I understood things well, wen we do the `getLastSentCertificateData` we relay on the LER for linking to a block number. So I guess that we should be consistent here. Otherwise we could send claims twice. Example:

- last block sent is 10
- block 18 includes a bridge => so a new LER
- block 20 includes a claim
- last block is 22

aggSender sends from 11 to 22

next iteration aggSender picks block 18 as last block sent as it matches with the last LER sent, and so it sends again the claim from block 20

2024-10-23 20:51 UTC, arnaubennassar commented on aggsender/aggsender.go
> +func (a *AggSender) shouldSendCertificate(block uint64) bool {
prolly a good idea to check if we've sent some cert that is still pending and return false if so

2024-10-23 20:51 UTC, arnaubennassar commented on aggsender/db/migrations/0001.sql
> +	certificate_id              VARCHAR NOT NULL,
fix identation

2024-10-23 20:51 UTC, arnaubennassar commented on aggsender/db/migrations/0001.sql
> +    PRIMARY KEY (height, certificate_id)
shouldnt `certificate_id` be enough for a primary key?

2024-10-23 20:51 UTC, arnaubennassar commented on bridgesync/migrations/bridgesync0001.sql
> +	global_index           	TEXT NOT NULL,
why this change?

2024-10-24 06:42 UTC, goran-ethernal commented on aggsender/aggsender.go
> +	bridges, err := a.l2Syncer.GetBridges(ctx, fromBlock, toBlock)
When you've processed blocks but don't have any bridges in them.

2024-10-24 06:43 UTC, goran-ethernal commented on aggsender/aggsender.go
> +	claims, err := a.l2Syncer.GetClaims(ctx, fromBlock, toBlock)
We will continue building certificate if we don't have claims (`len() == 0`). We are protecting our selves from block not processed in `toBlock, err := chooseToL2Block(lastL2Block.Number.Uint64(), lasL2BlockSynced, lastCertificateBlock)`.

2024-10-24 06:45 UTC, goran-ethernal commented on aggsender/aggsender.go
> +		lastSentCertificateHeader, err := a.aggLayerClient.GetCertificateHeader(lastSentCertificate.CertificateID)
I agree, but the only endpoint the `agglayer` has in `getCertificateHeader` which gets the certificate by its hash. If we don't have anything in our db, then there is no way to know what was last settled on the `agglayer`. We need to raise this with them.

2024-10-24 06:46 UTC, goran-ethernal commented on bridgesync/migrations/bridgesync0001.sql
> +	global_index           	TEXT NOT NULL,
The change on the bridge syncer db to store big int as TEXT was made because the sqlite kept saving big numbers with scientific annotation, for example if you have 810.000.000 it will save it as 8.1e9, and when reading it back to big int, big int throws an error.




NEW

[11:27](https://ethernalworkspace.slack.com/archives/D06H6U9QU9Z/p1729718857298149)
so we need to save it as TEXT so that sqlite dont do this magic with numbers and save them with exponents

2024-10-24 07:11 UTC, joanestebanr commented on aggsender/aggsender.go
> +func chooseToL2Block(lastL2Block, lasL2BlockSynced, lastCertificateBlock uint64) (uint64, error) {
The `fromBlock` is the block of last certificate + 1, so the case that you say the next certificate will start with **22+1**

2024-10-24 07:23 UTC, goran-ethernal commented on aggsender/aggsender.go
> +	l2Client         aggsendertypes.EthClient
Removed execution clients from aggsender: https://github.com/0xPolygon/cdk/pull/22/commits/df721ecca5dd141e832b1cd31e433bf43e6232db

2024-10-24 07:24 UTC, goran-ethernal commented on aggsender/aggsender.go
> +func (a *AggSender) shouldSendCertificate(block uint64) bool {
Fix: https://github.com/0xPolygon/cdk/pull/22/commits/df721ecca5dd141e832b1cd31e433bf43e6232db

2024-10-24 07:27 UTC, goran-ethernal commented on aggsender/db/migrations/0001.sql
> +    PRIMARY KEY (height, certificate_id)
Fix: https://github.com/0xPolygon/cdk/pull/22/commits/21680d828f80c61e923a2ce5d340d00c02dc3088

2024-10-24 07:27 UTC, goran-ethernal commented on aggsender/db/migrations/0001.sql
> +	certificate_id              VARCHAR NOT NULL,
Fix: https://github.com/0xPolygon/cdk/pull/22/commits/21680d828f80c61e923a2ce5d340d00c02dc3088

2024-10-24 07:35 UTC, goran-ethernal commented on aggsender/aggsender.go
> +func chooseToL2Block(lastL2Block, lasL2BlockSynced, lastCertificateBlock uint64) (uint64, error) {
Arnau is right, because in the case when we have previously sent a certificate, we will get the last block based on previous sent LER: `lastCertificateBlock, err = a.l2Syncer.GetBlockByLER(ctx, previousLocalExitRoot)`.

I'll change this so we return the `lastSentCertificate.ToBlock`.

2024-10-24 07:38 UTC, goran-ethernal commented on aggsender/aggsender.go
> +func chooseToL2Block(lastL2Block, lasL2BlockSynced, lastCertificateBlock uint64) (uint64, error) {
Fix: https://github.com/0xPolygon/cdk/pull/22/commits/d1e805ab5c3c288cc34814072c66e19732028c9f

2024-10-24 11:48 UTC, goran-ethernal commented on aggsender/aggsender.go
> +		lastSentCertificateHeader, err := a.aggLayerClient.GetCertificateHeader(lastSentCertificate.CertificateID)
We are talking with the agglayer team, so they will probably add a new rpc point for this.

2024-10-24 12:19 UTC, joanestebanr commented on aggsender/aggsender.go
> +		if lastSentCertificateHeader.Status == agglayer.InError {
it looks like in that case you don't set properly `lastCertificateBlock`

2024-10-24 14:04 UTC, goran-ethernal commented on aggsender/aggsender.go
> +		if lastSentCertificateHeader.Status == agglayer.InError {
Fixed: https://github.com/0xPolygon/cdk/pull/22/commits/335b15683579f711848d5c3f51de1ab7f26a3a75

2024-10-24 22:23 UTC, arnaubennassar approved these changes

2024-10-25 10:47 UTC, vcastellm commented on aggsender/config.go
> +	DBPath string `mapstructure:"DBPath"`
This could be renamed to StoragePath for consistency with other components, we can use this PR for that maybe?

2024-10-25 11:04 UTC, vcastellm commented on bridgesync/migrations/bridgesync0001.sql
> +	global_index           	TEXT NOT NULL,
Weird... is it a benefit to store this in strings and do the parsing on the app side? I'd say it's better to do this https://stackoverflow.com/a/40435685

2024-10-25 11:05 UTC, vcastellm commented on bridgesync/migrations/bridgesync0001.sql
> +	amount                  TEXT NOT NULL,
same for this

2024-10-25 11:05 UTC, vcastellm requested changes
Observe some comments

2024-10-25 11:13 UTC, vcastellm commented on bridgesync/migrations/bridgesync0001.sql
> +	global_index           	TEXT NOT NULL,
INTs in SQLite are 64 bit size so they are the same supported size as Postgres BIGINT, better to switch to INT?

2024-10-25 11:17 UTC, vcastellm commented on bridgesync/bridge_contract_test.go
> +	_, err := NewBridgeContract(common.Address{}, nil)
Is this test necessary?

2024-10-25 11:24 UTC, vcastellm commented on cmd/run.go
> +	"github.com/0xPolygon/cdk/aggsender"
duplicated?

2024-10-25 11:27 UTC, vcastellm commented on common/components.go
>  	PROVER = "prover"
not related to this PR but prover here?

2024-10-25 11:30 UTC, vcastellm commented on config/default.go
> +AggLayerURL = "https://agglayer-dev.polygon.technology"
Can I run without the agglayer? in other words, is this conditional with setting `SettlementBackend` in the aggregator?

2024-10-25 11:32 UTC, vcastellm commented on scripts/local_config
> +    # Maybe the file doesnt end with a new line so we added just in case
And this is why files should always end in new line 😁

2024-10-25 11:34 UTC, vcastellm commented on scripts/local_config
> +    echo " " >> $_TMP_FILE
This should be enough

```suggestion
    echo >> $_TMP_FILE
```

2024-10-28 15:23 UTC, joanestebanr commented on aggsender/config.go
> +	DBPath string `mapstructure:"DBPath"`
In fact, most of the  components used `DBPath`:bridgesync, claimsponsor, reorgdetector, l1infotreesync,....

2024-10-28 15:29 UTC, joanestebanr commented on common/components.go
>  	PROVER = "prover"
You're right  that is not a compoment, but I don't known if this is the best PR to fix this

2024-10-28 15:30 UTC, joanestebanr commented on config/default.go
> +AggLayerURL = "https://agglayer-dev.polygon.technology"
Sadly we don't have conditional config yet

2024-10-28 16:05 UTC, goran-ethernal commented on test/helpers/lxly-bridge-test.bash
> +    cat $bridge_deposit_file >&3
I am not sure what this line is. Might have been a leftover of some rebase.

2024-10-28 17:34 UTC, vcastellm commented on aggsender/config.go
> +	DBPath string `mapstructure:"DBPath"`
Yes but after that naming we decided naming it `StoragePath` in ethtxmanager see https://github.com/0xPolygon/cdk/blob/95cdb6afe1bbb14e5cf8e6f5e1fad3ac3c2681a6/config/default.go#L56 and the agreement was to update progressively the rest, why? Because it's called a `Storage` type not `DB` https://github.com/0xPolygon/cdk/pull/22/files#diff-e381a7a01497b1c89fcd51acf63d7f51713a9b25c747ed857fb0ba12b2bfca98R22 so for the sake of consistency it should be called Storage.

2024-10-28 17:36 UTC, vcastellm commented on cmd/run.go
> +	"github.com/0xPolygon/cdk/aggsender"
My mistake

2024-10-28 17:38 UTC, vcastellm commented on test/helpers/lxly-bridge-test.bash
> +    cat $bridge_deposit_file >&3
Remove?

2024-10-28 17:39 UTC, vcastellm commented on bridgesync/migrations/bridgesync0001.sql
> +	global_index           	TEXT NOT NULL,
@goran-ethernal not sure why it's not showing in the comments, but this is important

2024-10-28 17:40 UTC, vcastellm commented
This is being kept hidden by the GithubUI but it's important https://github.com/0xPolygon/cdk/pull/22#discussion_r1816496554

2024-10-28 19:22 UTC, goran-ethernal commented on bridgesync/migrations/bridgesync0001.sql
> +	global_index           	TEXT NOT NULL,
I mean we can, but I don't see a benefit. In text we can save it as a hash, or hex.

2024-10-28 19:57 UTC, goran-ethernal commented on aggsender/config.go
> +	DBPath string `mapstructure:"DBPath"`
Fix: https://github.com/0xPolygon/cdk/pull/22/commits/73188555ba2181303c9936c085fc0921997f7721

2024-10-28 21:01 UTC, arnaubennassar submitted a review, later dismissed
plz revert the changes done in https://github.com/0xPolygon/cdk/pull/140 before merging

2024-10-29 08:33 UTC, joanestebanr commented
> plz revert the changes done in #140 before merging

If we revert this PR we are going to have a bug if somebody calls `bridgeAsset` of Bridge Contract with param `forceUpdateGlobalExitRoot=false`. 
I suggest:
- Keep this code until we have a better solution (think in that as a workarround)   until contracts are updated as you suggest
- If we decide to delete this code we can implement a less efficient solution: 
    - add a check to the synced Bridge and if have `forceUpdateGlobalExitRoot=false` prevent syncing  this and keep in a 'waiting assets' lists on DB until appears a new  `bridgeAsset` with `forceUpdateGlobalExitRoot=true` that then we can include the 'waiting assets list' .This suppose that  in that in some moment there are going to be this call because the call `updateGlobalExitRoot()`that is supported in #140 solution is no longer supported.
 - Don't implement any solution to the bug and just detect it showing an error  and stopping syncing

2024-10-29 10:06 UTC, vcastellm commented on bridgesync/migrations/bridgesync0001.sql
> +	global_index           	TEXT NOT NULL,
well, there's some differences, int is not the same as bytes, less space, more performant, why you want to save an hex or hash in this field?

2024-10-29 10:08 UTC, vcastellm commented on bridgesync/migrations/bridgesync0001.sql
> +	amount              TEXT NOT NULL,
Same here, it can be INT, more performance less conversions on app side, less used space, direct mapping data model

2024-10-29 10:09 UTC, vcastellm commented on bridgesync/migrations/bridgesync0001.sql
> +	amount                  TEXT NOT NULL,
Same here, it can be INT, more performance less conversions on app side, less used space, direct mapping data model, etc. Let's check if that works

2024-10-29 10:28 UTC, goran-ethernal commented on bridgesync/migrations/bridgesync0001.sql
> +	amount              TEXT NOT NULL,
BigInt in Golang can be more than 64 bits. To humor you, I've set amount and global_index to integers and made a UT that stores a claim that has a large big.Int value in the global_index. It again stores the value with scientific annotation, and when we try to set the `big.Int.SetString` it fails:

```
meddler.WriteTargets: PostRead error on column [global_index]: big.Int.SetString failed on "1.8446744073709552e+19"
```

2024-10-29 10:31 UTC, goran-ethernal commented on bridgesync/migrations/bridgesync0001.sql
> +	amount              TEXT NOT NULL,
I've pushed the test: https://github.com/0xPolygon/cdk/pull/22/commits/12ca5ef16aaf1b04b49a177c9983b628eb5e4c33. You can try it yourself. Just change the column type in .sql file.

2024-10-29 14:10 UTC, vcastellm commented on bridgesync/migrations/bridgesync0001.sql
> +	amount              TEXT NOT NULL,
this is interesting, how do we would do in postgres? bigint or string? same here, if we need Go big ints then it's string if we are ok with Postgres Bigints then Ints here

2024-10-29 14:25 UTC, goran-ethernal commented on bridgesync/migrations/bridgesync0001.sql
> +	amount              TEXT NOT NULL,
I really don't know. Can't find any example currently on cdk repo, where we read something in postgress to a big.Int.

2024-10-29 15:21 UTC, vcastellm commented on bridgesync/migrations/bridgesync0001.sql
> +	global_index           	TEXT NOT NULL,
in this case, the global index is probably enough with SQLite INTs but it's not worth it

2024-10-29 15:22 UTC, vcastellm commented on bridgesync/migrations/bridgesync0001.sql
> +	amount              TEXT NOT NULL,
Ok, I checked it, wei can outgrow this type of field, so let's go with text.

2024-10-30 09:08 UTC, vcastellm approved these changes
![](https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExeTNhcDNnbnNqamZsMXd3ZXNuczAwNDY5MHcxbms3Y2h6bGo4aTBuaCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/YDSg8U0mJaJaw/giphy.webp)

2024-10-31 10:04 UTC, merged